"""Page 5: Ask the Data — natural-language Q&A over the NFL database (RAG)."""
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent.parent.parent))

import streamlit as st
from dashboard.utils import api_post

st.set_page_config(page_title="Ask the Data", page_icon="💬", layout="wide")
st.title("💬 Ask the Data")
st.caption("Ask natural-language questions about NFL stats (2016–2025). "
           "Answers are generated by retrieval-augmented generation over the database.")

EXAMPLES = [
    "Who had the most rushing yards in 2024?",
    "Which QB had the best completion rate last season?",
    "What was the win probability for the Chiefs in week 12 of 2024?",
    "Who led the NFL in receiving yards in 2023?",
]

with st.sidebar:
    st.subheader("Try an example")
    for ex in EXAMPLES:
        if st.button(ex, use_container_width=True):
            st.session_state["question"] = ex

question = st.text_input(
    "Your question",
    value=st.session_state.get("question", ""),
    placeholder="e.g. Who had the most rushing yards in 2024?",
)

if st.button("Ask", type="primary") or question:
    if not question.strip():
        st.stop()
    with st.spinner("Retrieving documents and generating an answer… "
                    "(the first request can take up to a minute if the API was idle)"):
        try:
            result = api_post("/ask", {"question": question, "k": 6})
        except Exception as e:
            st.error(f"Could not get an answer: {e}")
            st.stop()

    st.markdown("### Answer")
    st.markdown(result["answer"])

    with st.expander(f"Sources ({len(result['sources'])} documents retrieved)"):
        for i, s in enumerate(result["sources"], 1):
            st.markdown(
                f"**[{i}]** `{s['doc_type']}` · `{s['ref_id']}` · similarity {s['score']:.3f}"
            )
            st.caption(s["snippet"] + "…")

st.markdown("---")
st.caption("Retrieval: OpenAI text-embedding-3-small + pgvector cosine search · "
           "Generation: gpt-4o-mini grounded strictly in retrieved documents.")
